### ISSUE TITLE
HazelcastIntegrationTest.testIntegration

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast-zookeeper#4] opened 2016-09-30 13:30 UTC
```
java.lang.IllegalStateException: Error while talking to ZooKeeper. 
    at com.hazelcast.zookeeper.HazelcastIntegrationTest.testIntegration(HazelcastIntegrationTest.java:41)
Caused by: java.net.SocketException: No such device
    at com.hazelcast.zookeeper.HazelcastIntegrationTest.testIntegration(HazelcastIntegrationTest.java:41)
```

https://hazelcast-l337.ci.cloudbees.com/view/Plugins/job/Zookeeper/18/com.hazelcast$hazelcast-zookeeper/testReport/com.hazelcast.zookeeper/HazelcastIntegrationTest/testIntegration/

**Comment by jerrinot** [comment] 2016-09-30 14:12
now this a very nice failure! `Caused by: java.net.SocketException: No such device`

**Comment by lazerion** [comment] 2017-05-15 07:52
`no failure since 10/2016` closing after discussion with originator

**Closed by lazerion** 2017-05-15 07:52 UTC
Labels: bug
